# version: '3.9'

# services:
#   web:
#     image: event:0.0.1
#     build: .
#     ports:
#       - "8000:8000"

version: '3'

services:
  web:
    image: event:0.0.1
    build: .
    ports:
      - "8000:8000"
