version: '3.9'

services:
  web:
    image: event:0.0.1
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image : postgres
    environment : 
        POSTGRES_DB : event
        POSTGRES_USER : postgres
        POSTGRES_PASSWORD : admin

  redis:
    image: redis